USE ECOMMERCE_DB;
SHOW TABLES;

DESCRIBE CATEGORY;
SELECT * FROM CATEGORY;

DESCRIBE PRODUCT;
SELECT * FROM PRODUCT;

DESCRIBE TAG;
SELECT * FROM TAG;

DESCRIBE PRODUCT_TAG;
SELECT * FROM PRODUCT_TAG;

select *
from INFORMATION_SCHEMA.TABLE_CONSTRAINTS
where CONSTRAINT_SCHEMA = 'ECOMMERCE_DB';